# Node docker image on which this would be run
image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  script:
    - npm install

Test:
  stage: test
  script:
    - npm run test
    - npm run test-coverage

Deploy:
  stage: deploy
  script:
    - echo 'hello world'
  only:
    - xipu
